### ISSUE TITLE
To Yuchen

### ISSUE THREAD

**Issue by casnz1601** [nogibjj/IDS706_Fall2023_Final_Team_Project#1]
**_May your journey ahead be filled with success, happiness, and fulfillment as you graduate and embark on this new chapter, Yuchen. Congratulations! @yuchenz427._**
[🎵See You Again, Yuchen🎵](https://music.youtube.com/watch?v=xl8thVrlvjI&si=gbMqkHJ3Xjuhjj2i)
![WechatIMG3218](https://github.com/nogibjj/IDS706_Fall2023_Final_Team_Project/assets/44215173/af52eddf-f356-4be0-b8be-8b7ee3c2d8d9)

**Comment by yczhang-nv** [comment]
Appreciate it, Bryce! Looking forward to meeting you and your Maine Coon cats in Seattle! :)
